### ISSUE TITLE
z-wave settings page crashes with fibaro app/motion sensor zwave+

### ISSUE THREAD

**Issue by philsniff** [athombv/com.fibaro#36]
for two day all worked fine with my fibaro motion sensor (zwave+). but today motion detection suddenly won't stop.
so i reseted, exclude, reboot in all possible orders but ntotihng work like before .-(

what i discoverd: when i have the sensor paired and i make a motion detection my z-wave settings page (reset zwave, exclude device etc) in home crashed always!
all buttons are greyed out and flickered every 5 seconds for a millisecond...

i can reproduce this proceture. ptp homey -> zwave settingspage: ok -> pair motion sensor -> zwave settingspage ok -> force a motion detection => Z-WAVE SETTINGSOAGE CRASHES!

curious: all wored really fine since 0.9.2 and fibaro app 1.0.6
the problems happened suddently today..

i have only one fibaro motion sensor paired with homey and no other devieces so long (untill this really will work without problems for a while)

**Comment by philsniff** [comment]
the tip from @caseda to pull out the battery of the sensor for more than 15 seconds didn't bring it up

so every time the sensor makes its first detection the z-wave chip seems to be busy and doen't come back untill i reboot homey.

strange because i never had such problems before. suddently today.. and i have the only device paitred with homey is the sensor.

**Comment by caseda** [comment]
I might have seen where the problem lies.
I don't know if I will get to it for a fix today, since it will be a part of my parameters rewrite.

 But I can't confirm it since I don't have any Z-Wave+ motion detectors so I will be reliant on the community for trying it out

**Comment by philsniff** [comment]
thats ok, i can test for you but i have only some sparetime in the evening. (work till 7 PM, then family, an at 9 PM i could test)

so  wouldt be good when there are more testers ;-)

**Comment by RobinBol** [comment]
It is normal that the z-wave settings page greys out where the z-wave chip is busy. The currentProcess/currentCommand at the bottom of the page should then show what the chip is doing. How long does the page stays greyed out, and what are the currentProcess/currentCommand values?

**Comment by philsniff** [comment]
sorry, but i don't know what you mean with currentProcess/currentCommand Value or where i can see/get them.

when the page greys out  i only can reboot homey to have z-wave back. but i must deactivate the fibaro sensor because when it detects something the z-wave page grey out immediately.

i will test this evening more to give you more informations.

**Comment by caseda** [comment]
I have also never seen any process on what it's busy with on the settings page, only grayed out buttons. 
would have been helpful with debugging

**Comment by philsniff** [comment]
i can only underline what caseda says. i diidn't see any process things. at the bottom of the page is notinhg to see. or am i blind ;-)

**Comment by RobinBol** [comment]
Sorry, seems to be dev only info.

**Comment by philsniff** [comment]
that explains this phenomenon, lol

**Comment by caseda** [comment]
But I am a dev?
Or at least I have the developer menu item in settings.
Or there must be a dev part for athom people

**Comment by philsniff** [comment]
![schnappschuss_081116_085459_pm](https://cloud.githubusercontent.com/assets/7848863/17600944/0f0add24-6006-11e6-8dbc-1071d37f8f11.jpg)

**Comment by philsniff** [comment]
now exactly since isaved the sensor settings from work where  i couldn't wake up the device (b-button).
so it takes two hours untill the settings were saved because of the wake up time.

since then the z-wave settingspage looks like the screenshoz above

**Comment by caseda** [comment]
submitted a pull request with fix (hopefully) for your issue

**Comment by philsniff** [comment]
Thx caseda 

But why belongs  this issue only to me? But there is not much that i can make special...

Never the less: great that you are willing to fix that problem

**Comment by caseda** [comment]
Everybody's situation is different.
Can be an other device/any signal nearby that causes it for example. 

You're probably just the first one that bumps into it. 

Might just be a different cause then I expect. 
for example a weird situation occurred that the zwave driver didn't know how to handle and adjusted something that can only be fixed with a full reset of zwave network
(which is a thing you could try as well to see if that fixes it) 
Or a weird talking glitch with the communication of the zwave chip to homey which you again repair by pulling the plug of homey for multiple seconds. 

Just so many possibilities

**Comment by philsniff** [comment]
pull the plug: did it already for 3 or 4 times for 30 seconds.
full reset of zwave network? you mean the butoon in the zwave settings? dit it also already 9-10 times

i will see. thats something that will be fixed. 'just a question of time' (great depeche mode song by the way, lol)

ok, i will wait for your fix with your included pullrequest of the fibaro app. or can i test it someway before?

**Comment by caseda** [comment]
You can test it beforehand, if you know how to install apps from github then you can download my pull request:
https://github.com/caseda/com.fibaro

You might need to install the zwave driver if it gives an error while installing:
https://github.com/athombv/node-homey-zwavedriver

**Comment by philsniff** [comment]
i think i know how to do it.
i installed several other apps before with the athom-cli command line

i will try later this day. today is the last working day before 2 weeks holiday.
but i will at home and not flying away :-(

so i will have some more time for testing :-)

**Comment by philsniff** [comment]
hey caseda, sorry for the late reply but i was busy.
so now i installed your app (from link above) and  the z-wave driver, but my problem wasn't solved.

first motion detection: makes the z-wave chip busy and nothing comes back untill i reboot. :-(
i did all the things after this crash: pull the plug of homey for 30 seconds, after reboot z-wave ist ok, then i deinstalled the sensor-> but for that i had to klick 3 times the b-button=> z-wave crashed!

**Comment by caseda** [comment]
No problem at all :)
Check this one thing for me.
if my guess is right then your sensor is still in it's default parameters.
This makes it so any movement seen by the sensor itself lets the LED blink.

After 30 seconds of no motion does it show:
The LED blink according to temperature? (green = 5-15, lime = 15-22, yellow = 22-25, red is everything above)
Or is it flashing orange and then transitions to red

**Comment by philsniff** [comment]
- just disabled all other apps. only the fibaro app enabled.
- fibaro motion sensor + paired
- go to the z-wave settings page
- turned my notebook for better look at the page while i am going slowly in front of the sensor
-> BANG: it triggers/flashes my motion and in the same second the buttons of the z-wave page go grey out! ..  and never come back!

**Comment by philsniff** [comment]
tomorrow i will try to pair may fibaro door sensors .
i want to see if it is a sensor problem or a fibaro app/z-wave network problem.
seems that there is nobody with my problems, so it can be the sensor...

i will see

**Comment by philsniff** [comment]
oh sorry saw your answer right now: the led blinks according to the temperature (lime). not orange

**Comment by caseda** [comment]
Better that it becomes grey, then becoming bold :) (pulling all the hairs out)

really weird thing that is happening, can't tink of anything for fix now.
But indeed try the door sensor, if that works ok, its the sensor, if not its maybe homey, but lets not hope so.

**Comment by Inversion-NL** [comment]
It could also be the sensor.
Any possibility to pair this sensor to another Z-Wave network, like now.
Maybe it has gone bad, lately?

**Comment by philsniff** [comment]
No i have only homey as a z-Wave Controller. 
So i have to test in it is the sensor when i will pair my Door sensor. I will let you guys know. :-)

**Comment by Inversion-NL** [comment]
No friends, neighbors or family, maybe?

**Comment by philsniff** [comment]
LOL, oh i have friends. But nobody is on Home Automatation. The only one has a homatic system by telekom. No z-Wave

**Comment by Inversion-NL** [comment]
Lol, I wasn't implying you don't have any friends. If you thought I was, I'm sorry.
It's pity you can't double check the device.

**Comment by philsniff** [comment]
haha, i know that you didn't mean it how i wrote. but it was too cool to answer you in zhat way because someone could understood it in that way :-)

okay, now to something completely different:
i have to exclude my motion sensor becuase z-wave network crashed again and again.

now i includet the first time an other zwave device: the door/windows sensor (non zwave plus).
it works like a charm and my z-wave network is stable like it should!

does that mean that my motion sensor is broken? i think i must wait for some zwave tweenings in the future. perhaps my sensor won't do a brutal force an the zwave-network. i hope...

so it belongs to my motion sensor that my zwave network settings grey out and wont't come back.

so long guys

**Comment by Inversion-NL** [comment]
There are some issue with Z-Wave plus however they are with pairing.
You could wait a few firmware updates and try this one again.

**Comment by philsniff** [comment]
I will. Thx :-)

**Comment by philsniff** [comment]
i tested last evening my motion sensor plus and it worked very well!
no crashes, no greyed out zwave settings buttons.

so i will close this issue
